---
title: "AoC 2019"
output: html_notebook
---

DAY 2

```{r}
input2.19 <- read.csv("~/Documents/Data Science/Advent of Code/2019/Inputs/AoC 2019 - Day 2.rtf", 
                      header=FALSE, comment.char="#")
# PART 1

input2.19[157,1] = 0
input2.19 = input2.19[-c(1:8,158),]
input2.19[1]=1
input2.19[2]=12
input2.19[3]=2
input2.19 = as.numeric(input2.19)

for (i in 1:37){
  if (input2.19[(4*i)-3] == 1){
    input2.19[input2.19[(4*i)]+1] = input2.19[input2.19[(4*i)-2]+1] + input2.19[input2.19[(4*i)-1]+1]
  }
  if (input2.19[4*i-3] == 2){
    input2.19[input2.19[(4*i-3)+3]+1] = input2.19[input2.19[(4*i-3)+1]+1] * input2.19[input2.19[(4*i-3)+2]+1]
  }
  if (input2.19[4*i-3] == 99){break}
}
input2.19[1]

# PART 2


```

DAY 5

```{r}
library(stringr)
input5.19 <- read.csv("~/Documents/Data Science/Advent of Code/2019/Inputs/AoC 2019 - Day 5.txt", 
                      header=FALSE, comment.char="#")
df <- as.data.frame(t(as.matrix(input5.19)))
View(df)


# PART 1

input = 1
output = NA
i=1
while(i=1){
  j=1
  #INTCODE 1
  if (df[j,1] == 1){
    df[df[j+3,1]+1] = df[df[j+1,1]+1] + df[df[j+2,1]+1]
    l=4
  }
  #INTCODE 2
  if (df[j,1] == 2){
    df[df[j+3,1]+1] = df[df[j+1,1]+1] * df[df[j+2,1]+1]
    l=4
  }
  #INTCODE 3
  if (df[j,1] == 3){
    df[df[j+1,1]+1] = input
    l=2
  }
  #INTCODE 4
  if (df[j,1] == 4){
    output = df[df[j+1,1]+1]
    l=2
  }
  #ABORT
  if (df[j,1] == 99){
    i=0
  }
  
  if (df[j,1] > 99){
    code = toString(df[j,1])
    if (length(code) == 3){code = c_string(c("0", code), collapse="")}
    opcode = strtoi(str_sub(code, -1))
    mode1 = strtoi(str_sub(code, -3))
    mode2 = strtoi(str_sub(code, -4))
    
    if (opcode == "1"){
      df[df[j+3,1]+1] = df[df[j+1,1]+1] + df[df[j+2,1]+1]
    l=4
    }
  }
  
  j = j + l
}
output

c_string(c("0", toString(df[j,1])), collapse="")
```

