---
title: "Day 12"
output: html_notebook
---
PART 1

```{r}
rm(list = ls()) #Clear the environment
library(stringr)
in12 <- readLines("~/Classes/Advent of Code/Inputs/AoC - Day 12.txt")
test=c("F10", "N3", "F7", "R90", "F11")
View(in12)

# Set initial values

x = 0
y = 0
d = "E"
directions = c("E", "S", "W", "N")

# Define functions

move <- function(dir, mag, a, b){
  if (dir == "N"){b = b + mag}
  if (dir == "S"){b = b - mag}
  if (dir == "E"){a = a + mag}
  if (dir == "W"){a = a - mag}
  return (c(a,b))
}

turn <- function(dir, theta){
  t = theta/90
  i=0
  if (dir == "R"){i = match(d, directions) + t}
  if (i > 4){i = i - 4}
  if (dir == "L"){i = match(d, directions) - t}
  if (i < 1){i = i + 4}  
  return (directions[i])
}

# Loop through input

for (i in 1:length(in12)){
  if (str_detect(in12[i], "[NSWE]")){
    v = move(str_sub(in12[i],1,1), strtoi(str_sub(in12[i], 2, -1)), x, y)
    x = v[1]
    y = v[2]
  }
  if (str_detect(in12[i], "[RL]")){
    d = turn(str_sub(in12[i],1,1), strtoi(str_sub(in12[i], 2, -1)))
  }
  if (str_detect(in12[i], "F")){
    v = move(d, strtoi(str_sub(in12[i], 2, -1)), x, y)
    x = v[1]
    y = v[2]
  }
}
abs(x)+abs(y) 
```
PART 2

```{r}
# Set initial values
in12 = test
x = 0
y = 0
wp = c(10,1)
#d = "E"
directions = c("E", "S", "W", "N")

# Define functions

move <- function(dir, mag, a, b){
  if (dir == "N"){b = b + mag}
  if (dir == "S"){b = b - mag}
  if (dir == "E"){a = a + mag}
  if (dir == "W"){a = a - mag}
  return (c(a,b))
}

turn <- function(dir, theta, a, b){
if (dir == "R" && theta == 90){return (c(b, -a))}
if (dir == "R" && theta == 270){return (c(-b, a))}
if (theta == 180){return (c(-a, -b))}
if (dir == "L" && theta == 90){return (c(-b, a))}
if (dir == "L" && theta == 270){return (c(b, -a))}
}

# Loop through input

for (i in 1:length(in12)){
  if (str_detect(in12[i], "[NSWE]")){
    v = move(str_sub(in12[i],1,1), strtoi(str_sub(in12[i], 2, -1)), wp[1], wp[2])
    wp[1] = v[1]
    wp[2] = v[2]
  }
  if (str_detect(in12[i], "[RL]")){
    d = turn(str_sub(in12[i],1,1), strtoi(str_sub(in12[i], 2, -1)), wp[1], wp[2])
    wp[1] = d[1]
    wp[2] = d[2]
  }
  if (str_detect(in12[i], "F")){
    x = (strtoi(str_sub(in12[i], 2, -1)) * wp[1]) + x
    y = (strtoi(str_sub(in12[i], 2, -1)) * wp[2]) + y
  }
}
abs(x)+abs(y) #56578 too high
```

