---
title: "AoC 2020 - Day 23"
output: html_notebook
---

INPUT

```{r}
rm(list = ls()) #Clear the environment
library(stringr)
#library(hash)
#library(stringi)
in22 <- "156794823"
```

```{r}
part1 <- function(){
  in22 <- "156794823"
  c = 1
  for (i in 1:100){
    a = strtoi(str_sub(in22, c, c)) # number @ c
    x = str_sub(in22, c+1, c+3) #extracted numbers
    if (c == 7){x = str_c(x, str_sub(in22, 1, 1))}
    if (c == 8){x = str_c(x, str_sub(in22, 1, 2))}
    if (c == 9){x = str_c(x, str_sub(in22, 1, 3))}
    
    if (c <= 6) {in22 = str_c(str_sub(in22, 1, c), str_sub(in22, c+4, -1))}
    if (c == 7) {in22 = str_sub(in22, 2, 7)}
    if (c == 8) {in22 = str_sub(in22, 3, 8)}
    if (c == 9) {in22 = str_sub(in22, 4, 9)}
    
    b = a - 1
    if (b == 0){b = 9}
    while (str_detect(x, toString(b))){
      b = b - 1
      if (b == 0){b = 9}
      }
    d = str_locate(in22, toString(b))[1,1]
    #if (d == 10){d = 1}
    in22 = str_c(str_sub(in22, 1, d), x, str_sub(in22, d+1, -1))
    c = str_locate(in22, toString(a))[1,1]
    c = c + 1
    if (c == 10){c = 1}
  }
  return (in22)
}
in22
part1()
```
c=7, 8, 9?
