---
title: "AoC 2020 - Day 11"
output: html_notebook
author: "Joseph Richardson"
---

```{r}
rm(list = ls()) #Clear the environment
library(stringr)
in11 <- readLines("~/Documents/Data Science/Advent of Code/Inputs/AoC - Day 11.txt")
View(in11)

#PART 1

seats = c()
seats.og = c()
for (i in 1:length(in11)){
  row = c()
  for (j in 1:98){
    if (str_sub(in11[i], j, j) == "."){row = cbind(row, 0)}
    if (str_sub(in11[i], j, j) == "L"){row = cbind(row, 1)}
    if (str_sub(in11[i], j, j) == "#"){row = cbind(row, 2)}
  }
  seats.og = as.matrix(rbind(seats.og, row))
}

seats = seats.og
diff = T
temp = seats
while (diff == T){
  total = 0
  for (i in 1:nrow(seats)){
    for (j in 1:ncol(seats)){
      c=-1
      k=-1
      
      if (seats[i,j] == 1){
        c = 0 #count of non-L (non-empty) seats (1)
        if (i-1 > 0 && j-1 > 0){if (seats[(i-1), (j-1)] == 2){c = c + 1}} #Up & Left
        if (i-1 > 0){if (seats[(i-1), j] == 2){c = c + 1}} #Up
        if (i-1 > 0 && j+1 <= ncol(seats)){if (seats[(i-1), (j+1)] == 2){c = c + 1}} #Up & Right
        if (j-1 > 0){if (seats[i, (j-1)] == 2){c = c + 1}} #Left
        if (j+1 <= ncol(seats)){if (seats[i, (j+1)] == 2){c = c + 1}} #Right
        if (i+1 <= nrow(seats) && j-1 > 0){if (seats[(i+1), (j-1)] == 2){c = c + 1}} #Down & Left
        if (i+1 <= nrow(seats)){if (seats[(i+1), j] == 2){c = c + 1}} #Down
        if (i+1 <= nrow(seats) && j+1 <= ncol(seats)){if (seats[(i+1), (j+1)] == 2){c = c + 1}} #Down & Right
      }
      
      if (seats[i,j] == 2){
        total = total + 1
        k = 0 #count of # (occupied) seats (2)
        if (i-1 > 0 && j-1 > 0){if (seats[(i-1), (j-1)] == 2){k = k + 1}} #Up & Left
        if (i-1 > 0){if (seats[(i-1), j] == 2){k = k + 1}} #Up
        if (i-1 > 0 && j+1 <= ncol(seats)){if (seats[(i-1), (j+1)] == 2){k = k + 1}} #Up & Right
        if (j-1 > 0){if (seats[i, (j-1)] == 2){k = k + 1}} #Left
        if (j+1 <= ncol(seats)){if (seats[i, (j+1)] == 2){k = k + 1}} #Right
        if (i+1 <= nrow(seats) && j-1 > 0){if (seats[(i+1), (j-1)] == 2){k = k + 1}} #Down & Left
        if (i+1 <= nrow(seats)){if (seats[(i+1), j] == 2){k = k + 1}} #Down
        if (i+1 <= nrow(seats) && j+1 <= ncol(seats)){if (seats[(i+1), (j+1)] == 2){k = k + 1}} #Down & Right
      }
      if (c == 0){temp[i,j] = 2}
      if (k >= 4){temp[i,j] = 1}
    }
  }
  if (all((temp == seats), TRUE)){diff = F}
  seats = temp
}
total
```
```{r}
# PART 2

seats = seats.og
diff = T
temp = seats
while (diff == T){
  total = 0
  for (i in 1:nrow(seats)){
    for (j in 1:ncol(seats)){
      c=-1
      k=-1
      
      if (seats[i,j] == 1){
        c = 0 #count of non-L (non-empty) seats (1)
        
        #Up & Left
        x=1
        y=1
        pos = seats[i-y, j-x]
        edge = F
        while(pos == 0  || edge = F){
          if (i-y > 0 && j-x > 0){
            x=x-1
            y=y-1}
          else {edge = T}
        }
        if (pos == 2 || edge == F){c = c + 1}} 
      
        if (i-1 > 0){if (seats[(i-1), j] == 2){c = c + 1}} #Up
        if (i-1 > 0 && j+1 <= ncol(seats)){if (seats[(i-1), (j+1)] == 2){c = c + 1}} #Up & Right
        if (j-1 > 0){if (seats[i, (j-1)] == 2){c = c + 1}} #Left
        if (j+1 <= ncol(seats)){if (seats[i, (j+1)] == 2){c = c + 1}} #Right
        if (i+1 <= nrow(seats) && j-1 > 0){if (seats[(i+1), (j-1)] == 2){c = c + 1}} #Down & Left
        if (i+1 <= nrow(seats)){if (seats[(i+1), j] == 2){c = c + 1}} #Down
        if (i+1 <= nrow(seats) && j+1 <= ncol(seats)){if (seats[(i+1), (j+1)] == 2){c = c + 1}} #Down & Right
      }
      
      if (seats[i,j] == 2){
        total = total + 1
        k = 0 #count of # (occupied) seats (2)
        if (i-1 > 0 && j-1 > 0){if (seats[(i-1), (j-1)] == 2){k = k + 1}} #Up & Left
        if (i-1 > 0){if (seats[(i-1), j] == 2){k = k + 1}} #Up
        if (i-1 > 0 && j+1 <= ncol(seats)){if (seats[(i-1), (j+1)] == 2){k = k + 1}} #Up & Right
        if (j-1 > 0){if (seats[i, (j-1)] == 2){k = k + 1}} #Left
        if (j+1 <= ncol(seats)){if (seats[i, (j+1)] == 2){k = k + 1}} #Right
        if (i+1 <= nrow(seats) && j-1 > 0){if (seats[(i+1), (j-1)] == 2){k = k + 1}} #Down & Left
        if (i+1 <= nrow(seats)){if (seats[(i+1), j] == 2){k = k + 1}} #Down
        if (i+1 <= nrow(seats) && j+1 <= ncol(seats)){if (seats[(i+1), (j+1)] == 2){k = k + 1}} #Down & Right
      }
      if (c == 0){temp[i,j] = 2}
      if (k >= 4){temp[i,j] = 1}
    }
  }
  if (all((temp == seats), TRUE)){diff = F}
  seats = temp
}
total
```


