---
title: "AoC 2020"
output:
  html_document:
    df_print: paged
  word_document: default
  pdf_document: default
---

DAY 1
  
```{r}
input1 <- read.table("C:/Users/Joe/Downloads/AoC_ Input 1 - Sheet1.csv", quote="\"", comment.char="")
View(input1)

product=0
for (i in 1:200){
  for (j in i:200){
    for (k in j:200){
      if (input1$V1[i]+input1$V1[j]+input1$V1[k] == 2020){
        product=input1$V1[i]*input1$V1[j]*input1$V1[k]
      }
    }
  }
}

input1$V1[2]
product
```
  
DAY 2
  
```{r}
library(stringr)
input2 <- read.table("~/Documents/Data Science/Advent of Code/Aoc - Day 2 - Sheet1.csv", 
                     quote="\"", comment.char="")
#View(input2)

#PART 1
valid.count = 0
for (i in 1:1000){
  min = strtoi(unlist(str_extract_all(input2[i,1], "[^-]+")))[1]
  max = strtoi(unlist(str_extract_all(input2[i,1], "[^-]+")))[2]
  letter = unlist(str_extract_all(input2[i,2], "[^:]+"))
  frequency = str_count(input2[i,3], letter)
  if (frequency >= min & frequency <= max){valid.count = valid.count + 1}
}
valid.count

#PART 2
valid.count = 0
for (i in 1:1000){
  first = strtoi(unlist(str_extract_all(input2[i,1], "[^-]+")))[1]
  second = strtoi(unlist(str_extract_all(input2[i,1], "[^-]+")))[2]
  letter = unlist(str_extract_all(input2[i,2], "[^:]+"))
  count = 0
  if (str_sub(input2[i,3], first, first) == letter){count = count + 1}
  if (str_sub(input2[i,3], second, second) == letter){count = count + 1}
  if (count == 1){valid.count = valid.count + 1}
}
valid.count
```

DAY 3

```{r}
rm(list=ls())
library(stringr)
input3 <- read.csv2("~/Documents/Data Science/Advent of Code/Inputs/AoC - Day 3 - Sheet1.csv",
                    header=FALSE, row.names=NULL, sep="")
View(input3)

# PART 1

c=1
trees=0
for (r in 2:323){
  c=c+3
  if (c > 31){c = c - 31}
  if (str_sub(input3[r, 1], c, c) == "#"){trees = trees + 1}
  r=r+1
}
trees

# PART 2

slopes = matrix(c(1,3,5,7,1,1,1,1,1,2), nrow=5, ncol=2)
outcomes = c()
for (i in 1:nrow(slopes)){
  c=1
  r=1
  trees=0
  for (j in 1:323){
    r=r+slopes[i,2]
    if (r > nrow(input3)){break}
    c = c + slopes[i,1]
    if (c > 31){c = c - 31}
    if (str_sub(input3[r, 1], c, c) == "#"){trees = trees + 1}
  }
  outcomes = cbind(outcomes, trees)
}
prod(outcomes)
```

DAY 4

```{r}
rm(list=ls())
library(stringr)
input4 = readLines("~/Documents/Data Science/Advent of Code/Inputs/AoC - Day 4.txt")
test = readLines("~/Documents/Data Science/Advent of Code/Inputs/AoC - Day 4 test.txt")

head(input4)

# PART 1

counts = 0
count = 0
for (i in 1:length(input4)){
  
  if (str_detect(input4[i], "byr")){count = count + 1}
  if (str_detect(input4[i], "iyr")){count = count + 1}
  if (str_detect(input4[i], "eyr")){count = count + 1}
  if (str_detect(input4[i], "hgt")){count = count + 1}
  if (str_detect(input4[i], "hcl")){count = count + 1}
  if (str_detect(input4[i], "ecl")){count = count + 1}
  if (str_detect(input4[i], "pid")){count = count + 1}
  if (input4[i] == "" || i == length(input4)){
    if (count == 7){counts = counts + 1}
    count=0
  }
}
counts

# PART 2

eyes = c("amb", "blu", "brn", "gry", "grn", "hzl", "oth")
counts = 0
count = 0
for (i in 1:length(input4)){
  if (input4[i] == ""){input4[i] = "x"}
  line = unlist(strsplit(input4[i], " "))
  for (j in 1:length(line)){
    if (str_detect(line[j], "byr")){
      if(sub("*byr:", "", line[j]) >= 1920 && sub("*byr:", "", line[j]) <= 2002){
        if (str_count(sub("*byr:", "", line[j]), "[1234567890]") == 4){count = count + 1}
      }
    }
    if (str_detect(line[j], "iyr")){
      if(sub("*iyr:", "", line[j]) >= 2010 && sub("*iyr:", "", line[j]) <= 2020){
        if (str_count(sub("*iyr:", "", line[j]), "[1234567890]") == 4){count = count + 1}
      }
    }
    if (str_detect(line[j], "eyr")){
      if(sub("*eyr:", "", line[j]) >= 2020 && sub("*eyr:", "", line[j]) <= 2030){
        if (str_count(sub("*eyr:", "", line[j]), "[1234567890]") == 4){count = count + 1}
      }
    }
    if (str_detect(line[j], "hgt")){
      if(str_detect(line[j], "in")){
        number = strtoi(sub("in.*", "", sub("*hgt:", "", line[j])))
        if(number  >= 59 && number <= 76){count = count + 1}
      }
      if(str_detect(line[j], "cm")){
        number = strtoi(sub("cm.*", "", sub("*hgt:", "", line[j])))
        if(number  >= 150 && number <= 193){count = count + 1}
      }
    }
    if (str_detect(line[j], "hcl")){
      hcl = sub("*hcl:", "", line[j])
      if (str_sub(hcl, 1, 1) == "#" && str_count(hcl, "[abcdefghijklmnopqrstuvwxyz0123456789]") == 6){
        count = count + 1
        }
    }
    if (str_detect(line[j], "ecl")){
      for (m in 1:length(eyes)){
        if(str_detect(sub("*ecl:", "", line[j]), eyes[m]) && 
          str_length(sub("*ecl:", "", line[j])) == 3) {count = count + 1}
      }
    }
    if (str_detect(line[j], "pid")){
      if(str_count(sub("*pid:", "", line[j]), "[1234567890]") == 9){count = count + 1}
    }
  }
  if(input4[i] == "x" || i == length(input4)){if(count == 7){counts = counts + 1}
    count=0
    }
  }
counts
```

DAY 5

```{r}

```

DAY 6

```{r}

```

DAY 7

```{r}

```

DAY 8

```{r}

```

DAY 9

```{r}

```

DAY 10

```{r}

```

